### ISSUE TITLE
CommandError: No fixture named 'initial_role' found.

### ISSUE THREAD

**Issue by scharph** [htdvisser/taiga-docker#34]
i did `docker-compose -f taiga.yml`

taiga.yml:

```
data:
  image: tianon/true
  volumes:
    - /var/lib/postgresql/data
    - /usr/local/taiga/media
    - /usr/local/taiga/static
    - /usr/local/taiga/logs

db:
  image: postgres
  environment:
    POSTGRES_USER: taiga
    POSTGRES_PASSWORD: password
  volumes_from:
    - data
  restart: always

taigaback:
  build: taiga-back
  hostname: dev.example.com
  environment:
    SECRET_KEY: examplesecretkey
    EMAIL_USE_TLS: 'True'
    EMAIL_HOST: smtp.gmail.com
    EMAIL_PORT: 587
    EMAIL_HOST_USER: mygmail@gmail.com
    EMAIL_HOST_PASSWORD: mypassword
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  links:
    - db:postgres
  volumes_from:
    - data
  restart: always

taigafront:
  build: taiga-front-dist
  hostname: 0.0.0.0
  links:
    - taigaback
  volumes_from:
    - data
  ports:
    - 0.0.0.0:9000:80
  restart: always
```

root@ds:/usr/local/taiga/taiga-back# python manage.py loaddata initial_role
Trying import local.py settings...
CommandError: No fixture named 'initial_role' found.
